### ISSUE TITLE
Support dependency definitions inside Chart.yaml

### ISSUE THREAD

**Issue by very-doge-wow** [very-doge-wow/stella#27]
**Is your feature request related to a problem? Please describe.**
Currently dependencies are only read from a requirements.yaml.
However, one can also specifiy those inside the Chart.yaml as well.
That data should also be used for doc generation, if present.

**Describe the solution you'd like**
Check if dependencies are listed in Chart.yaml

**Describe alternatives you've considered**

**Additional context**
Example inside Chart.yaml:

```yaml
dependencies:
  - name: kube-state-metrics
    version: "4.7.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeStateMetrics.enabled
```

cc @very-doge-wow
